learning_log/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),

]

learning_logs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    #index
    url(r'^$', views.index, name='index'),

    #topics
    url(r'^topics/$', views.topics, name='topics'),

    #topic_detail page
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    #page to add new topic
    url(r'^new_topic/$', views.new_topic, name='new_topic'),

    #page to add new entry
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),

    #page edit entry
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),

    #search results
    url(r'^search_results/$', views.search_results, name='search_results'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$',views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    text=models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        return self.text

class Entry(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text= models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model=Topic
        fields=['text']
        labels={'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model=Entry
        fields=['text']
        labels={'text':''}
        widgets={'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.db.models import Q


# Create your views here.
def index(request):
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics' : topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner!=request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form' : form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method !='POST':
        form = EntryForm()
    else:
        form=EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))
    context = {'topic':topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner!=request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))
    
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

@login_required
def search_results(request):
    query = request.GET.get('q','')
    #The empty string handles an empty "request"
    if query:
            queryset = (Q(text__icontains=query))
            #I assume "text" is a field in your model
            #i.e., text = model.TextField()
            #Use | if searching multiple fields, i.e., 
            #queryset = (Q(text__icontains=query))|(Q(other__icontains=query))
            #value = Topic.objects.filter(queryset).distinct().values("text")
            
            value = Topic.objects.filter(queryset).distinct().values_list("text",flat=True)
            newValue=Topic.objects.get(text=value)
            results = Entry.objects.filter(topic=newValue)
            topic = newValue
            #value = Topic.objects.filter(queryset).distinct().values()
            #import pdb; pdb.set_trace()

    else:
       results = []
    context = {'topic':topic,'results':results,'query':query}
    return render(request, 'learning_logs/search_results.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
# Create your views here.

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    
    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset = "utf-8">
        <meta http-equiv="X-UA-Compatiable" content="IE=edge">
        <title>learning notes</title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}

    </head>
</html>
<body>
    <nav class="navbar navbar-inverse navbar-static-top">
        <div class="container">
            <div class="navbar-heder">
                <a class="navbar-brand" href="{% url 'learning_logs:index' %}">learning log</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'learning_logs:topics' %}">Topics</a> </li>                    
                </ul>
                <form class="navbar-form navbar-left" method ="GET" action="{% url 'learning_logs:search_results' %}">
                    <div class="form-group">
                      <input type="text" name="q" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" value="{{ query|escape }}" class="btn btn-default">GO</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <p class="navbar-text">Hello, {{ user.username }}.</p>
                    <li><a href="{% url 'users:logout' %}">log out</a></li>
                    {% else %}
                    <li><a href="{% url 'users:register' %}"><span class="glyphicon glyphicon-user"></span> register</a></li>
                    <li><a href="{% url 'users:login' %}"><span class="glyphicon glyphicon-log-in"></span> log in</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

<div class="container">
    <div class="page-header">
        {% block header %}{% endblock header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</div>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
    <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
{% endblock header %}

{% block content %}
    <p>edit entry:</p>
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button name="submit" class="btn btn-default">save changes</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
<div class="jumbotron">
    <h1>Track your learning</h1>
    <p>
        <a href="{% url 'users:register' %}">Register an account</a> to make your own Learning notes, and list the topics you are learning about.
    </p>
    <p>
        Whenever you learning something new, make it an entry!
    </p>
</div>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
    <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
{% endblock header %}

{% block content %}  
    <p>Add a new entry:</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button name="submit" class="btn btn-default">Add entry</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}
{% block content %}
    <form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button name="submit" class="btn btn-default">add topic</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/search_results.html
{% extends "learning_logs/base.html" %}
{% block content %}
{% if query %}
    {% if results %}
    <h4>{{ topic }}</h4>
    <ul>
    {% for item in results%}
        <li>{{ item|escape }}</li>
    {% endfor %}
    </ul>
    {% else %}
       <p>Query returned no results.</p>
    {% endif %}
{% endif %} 
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}
{% block header %}
    <h2><a href="{% url 'learning_logs:topics' %}" style="color:black">Topic</a>: {{ topic }}</h2>
{% endblock header %}

{% block content %}

<h4>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
</h4>
<ul>
{% for entry in entries %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4>{{ entry.date_added|date:'M d, Y H:i' }}
            </h4>
        </div>
        <div class="panel-body">
            {{ entry.text|linebreaks }}
        </div>
        <div class="panel-footer">
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
        </div>
    </div>
{% empty %}
    <h3>
        There are no entries for this topic yet.
    </h3>
{% endfor %}


{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block header %}
    <h2>Topics</h2>
{% endblock header %}

{% block content %}
    
    <div class="list-group">
        {% for topic in topics %}
            <h3><a href="{% url 'learning_logs:topic' topic.id %}" class="list-group-item">{{ topic }}</a></h3>
        {% empty %}
            <li>No topics have been added yet.</li>
        {% endfor %}
        </div>
        <h4><a href="{% url 'learning_logs:new_topic' %}">add a new topic</a></h4>
{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}
    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
        <button name="submit" class="btn btn-default">log in</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>
{% endblock content %} 

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Register</h2>
{% endblock header %}
{% block content %}
    <form method="post" action="{% url 'users:register' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button name="submit" class="btn btn-default">register</button>
        {% endbuttons %}
        <input type="hidden" name="text" value="{% url 'learning_logs:index' %}" />
    </form>
{% endblock content %} 